### ISSUE TITLE
Serialize is not a function error

### ISSUE THREAD

**Issue by MateMalice** [jsreport/jsreport-fs-store-azure-sb-sync#1]
**Problem description**
Since v 1.1.0, an error is thrown during reporter initialisation that did not happen before. The output  log from reporter initialisation is as follows:
```2020-03-04T01:03:58.354Z - info: Initializing jsreport@2.6.1 in production mode using configuration file: jsreport.config.json
2020-03-04T01:03:58.358Z - info: Searching for available extensions in /app/
2020-03-04T01:03:58.376Z - info: Extensions location cache not found, crawling directories
2020-03-04T01:03:58.687Z - info: Found 46 extensions
2020-03-04T01:03:58.977Z - info: Setting dedicated-process (process based) strategy for rendering. Please visit http://jsreport.net/learn/configuration for information how to get more performance.
2020-03-04T01:03:58.985Z - info: Using extension import-export@1.4.0
2020-03-04T01:03:59.054Z - info: Using extension templates@2.3.2
2020-03-04T01:03:59.058Z - info: Using extension azure-storage@1.1.0
2020-03-04T01:03:59.191Z - info: Using extension tags@2.3.0
2020-03-04T01:03:59.193Z - info: Using extension jsrender@2.1.1
2020-03-04T01:03:59.194Z - info: Using extension authentication@2.3.0
2020-03-04T01:03:59.217Z - info: Using extension handlebars@2.1.0
2020-03-04T01:03:59.219Z - info: Using extension cli@2.1.1
2020-03-04T01:03:59.220Z - info: Using extension freeze@2.0.0
2020-03-04T01:03:59.222Z - info: Using extension debug@2.1.1
2020-03-04T01:03:59.223Z - info: Using extension fop-pdf@2.2.0
2020-03-04T01:03:59.257Z - info: Using extension ejs@2.2.0
2020-03-04T01:03:59.258Z - info: Using extension express@2.5.0
2020-03-04T01:03:59.351Z - info: Using extension pdf-password@2.2.0
2020-03-04T01:03:59.401Z - info: Using extension docx@2.3.1
2020-03-04T01:03:59.420Z - info: Using extension fs-store@2.6.0
2020-03-04T01:03:59.573Z - info: fs store underlying changes synchronization with studio is disabled
2020-03-04T01:03:59.574Z - info: Using extension chrome-pdf@1.6.1
2020-03-04T01:03:59.632Z - info: Using extension authorization@2.2.5
2020-03-04T01:03:59.635Z - info: Using extension html-to-text@2.1.0
2020-03-04T01:03:59.638Z - info: Using extension child-templates@1.3.0
2020-03-04T01:03:59.641Z - info: Using extension browser-client@2.2.1
2020-03-04T01:03:59.643Z - info: Using extension licensing@2.1.2
2020-03-04T01:03:59.645Z - info: Using extension pdf-meta@0.2.0
2020-03-04T01:03:59.647Z - info: Using extension data@2.1.0
2020-03-04T01:03:59.648Z - info: Using extension pdf-utils@1.5.2
2020-03-04T01:03:59.818Z - info: Using extension pptx@0.4.1
2020-03-04T01:03:59.823Z - info: Using extension wkhtmltopdf@2.2.0
2020-03-04T01:03:59.874Z - info: Using extension reports@2.2.0
2020-03-04T01:03:59.877Z - info: Using extension version-control@1.3.2
2020-03-04T01:03:59.920Z - info: Using extension text@2.0.0
2020-03-04T01:03:59.921Z - info: Using extension static-pdf@0.3.1
2020-03-04T01:03:59.923Z - info: Using extension studio@2.6.6
2020-03-04T01:04:00.027Z - info: Using extension base@2.0.2
2020-03-04T01:04:00.029Z - info: Using extension html-embedded-in-docx@2.2.0
2020-03-04T01:04:00.031Z - info: Using extension fs-store-azure-sb-sync@1.1.0
2020-03-04T01:04:00.154Z - info: Using extension scheduling@2.1.1
2020-03-04T01:04:00.247Z - info: Using extension scripts@2.2.1
2020-03-04T01:04:00.252Z - info: Using extension fs-store-azure-storage-persistence@1.1.0
2020-03-04T01:04:00.361Z - info: Using extension html-to-xlsx@2.4.1
2020-03-04T01:04:00.419Z - info: html-to-xlsx detected chrome as available html engine
2020-03-04T01:04:00.420Z - info: Using extension studio-theme-dark@0.2.0
2020-03-04T01:04:00.421Z - info: Using extension assets@1.5.1
2020-03-04T01:04:00.428Z - info: Using extension pdf-sign@0.4.0
2020-03-04T01:04:00.430Z - info: Using extension xlsx@2.2.1
2020-03-04T01:04:00.509Z - info: Using extension sample-template@2.4.0
2020-03-04T01:04:00.512Z - info: Using extension resources@2.0.3
2020-03-04T01:04:00.514Z - info: Using extension public-templates@2.1.0
2020-03-04T01:04:00.517Z - info: Using fs provider for template store.
2020-03-04T01:04:00.524Z - info: fs store is persisting using azure-storage
2020-03-04T01:04:00.571Z - info: fs store is synchronizing using azure-sb
2020-03-04T01:04:00.668Z - info: fs store is loading data
2020-03-04T01:04:23.130Z - info: fs store is initialized successfully
2020-03-04T01:04:23.223Z - error: Error occured during reporter init TypeError: serialize is not a function
    at Object.publish (/app/node_modules/jsreport-fs-store-azure-sb-sync/lib/syncAzureServiceBus.js:72:53)
    at Object.queue.push [as fn] (/app/node_modules/jsreport-fs-store/lib/provider.js:126:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
TypeError: serialize is not a function
    at Object.publish (/app/node_modules/jsreport-fs-store-azure-sb-sync/lib/syncAzureServiceBus.js:72:53)
    at Object.queue.push [as fn] (/app/node_modules/jsreport-fs-store/lib/provider.js:126:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

As a result of this error, jsreport does not start.

**Steps to reproduce**
I built jsreport for Docker (it is running in Kubernetes) and added this extension to the Dockerfile. I passed in the environment variables needed to configure Azure blob storage, service bus, etc. as per the relevant instructions.

This problem did not occur with the previous version and from checking the source code at /lib/syncAzureServiceBus.js, it appears that the new version does not define "serialize" as described in the error output. 

Please let me know if you need help fixing this - I am going to roll back to the previous version until it is fixed, but I am reluctant to make my own changes without knowing the reason for the changes to the serialisation methods and why the old ones were removed as imports. Happy to help get this working if someone can explain this. :-)

**Comment by pofider** [comment]
Thank you for the very complete problem description. This is very rare :)

The problem is that the 1.1.0 release is compatible just with jsreport-fs-store@2.7.1 as noted in the [release notes](https://github.com/jsreport/jsreport-fs-store-azure-sb-sync/releases/tag/1.1.0).
We are currently in the middle of releasing jsreport@2.7.0 so afterward the versions will match better. We have also plan to add a better extensions dep versions handling to jsreport core in the future.

At this moment better downgrade the jsreport-fs-store-azure-sb-sync  or update jsreport-fs-store to the latest.
